(function (root) {
  'use strict';
  const fr = {
    "app.name": "WeatherScope",
    "app.title": "WeatherScope - Prévisions climatiques et urbaines",
    "app.description": "Recherchez les conditions météorologiques en temps réel par nom de ville ou découvrez des villes du monde entier répondant à vos conditions climatiques préférées.",
    "app.noscript": "WeatherScope nécessite l'activation de JavaScript pour récupérer et afficher des données météorologiques en direct.",
    "app.noscriptHint": "Veuillez activer JavaScript dans votre navigateur et recharger la page.",
    "nav.modeAria": "Sélection du mode de recherche",
    "nav.citySearch": "Recherche de ville",
    "nav.compare": "Comparer",
    "nav.climateFilter": "Filtre climatique",
    "nav.cameras": "Caméras en direct",
    "nav.unitAria": "Sélection de l'unité de température",
    "nav.languageAria": "Sélection de la langue",
    "nav.yourTime": "Votre heure",
    "nav.searchModeCity": "Recherche de ville",
    "nav.searchModeCompare": "Comparer",
    "nav.searchModeClimate": "Filtre climatique",
    "nav.searchModeCameras": "Caméras en direct",
    "search.placeholderCity": "Rechercher une ville (par exemple Paris, Tokyo, New York)...",
    "search.placeholderCompare": "Ajoutez un emplacement à comparer (par exemple Athènes, Oslo, Le Caire)...",
    "search.placeholderClimate": "Climat de recherche : par ex. Ensoleillé, chaud, pluie, neige, > 25°C, froid < 10°C...",
    "search.placeholderCameras": "Villes avec caméras : Londres, Seattle, Toronto...",
    "search.submit": "Recherche",
    "search.inputAria": "Rechercher une ville ou une condition climatique",
    "search.clearAria": "Effacer la saisie",
    "search.suggestionsAria": "Suggestions de recherche",
    "search.useLocation": "Utiliser l'emplacement actuel",
    "search.searchingFor": "Recherche de \"{city}\"...",
    "search.matchingLocations": "Emplacements correspondants {count} - sélectionnez-en un",
    "climate.presetClimates": "Climats prédéfinis :",
    "climate.sunny": "Ensoleillé",
    "climate.cloudy": "Nuageux",
    "climate.rainy": "Pluvieux",
    "climate.snowy": "Neigeux",
    "climate.storm": "Tempête",
    "climate.freezing": "Gel",
    "climate.cold": "Froid",
    "climate.cool": "Frais",
    "climate.mild": "Doux",
    "climate.warm": "Chaud",
    "climate.hot": "Très chaud",
    "climate.humid": "Humide",
    "climate.dry": "Sec",
    "climate.windy": "Venteux",
    "climate.gale": "Coup de vent",
    "climate.beachDay": "Journée à la plage",
    "climate.skiTrip": "Séjour au ski",
    "climate.tropical": "Tropical",
    "climate.mildBreezy": "Doux avec une légère brise",
    "climate.rainyMild": "Pluvieux et doux",
    "climate.resultsTitle": "Des villes adaptées aux conditions climatiques",
    "climate.resultsAria": "Villes correspondantes",
    "climate.foundOne": "Ville {count} trouvée",
    "climate.foundMany": "{count} villes trouvées",
    "climate.resultsSubtitle": "Recherche des villes de référence {count} dans le monde entier. Cliquez sur n’importe quelle ville pour découvrir sa météo détaillée en temps réel et ses perspectives sur 7 jours.",
    "climate.clickToExplore": "Cliquez sur n'importe quelle carte de ville pour découvrir sa météo détaillée en temps réel et ses perspectives sur 7 jours.",
    "climate.sortLabel": "Trier:",
    "climate.sortNameAsc": "Nom de la ville (A-Z)",
    "climate.sortNameDesc": "Nom de la ville (Z-A)",
    "climate.sortTemperature": "Température",
    "climate.sortHumidity": "Humidité",
    "climate.sortWind": "Vitesse du vent",
    "climate.sortHighToLow": "{label} (de haut en bas)",
    "climate.sortLowToHigh": "{label} (du plus bas au plus haut)",
    "climate.emptyTitle": "Aucune ville de l'ensemble de données de référence {count}-city ne correspond actuellement à ces critères climatiques exacts.",
    "camera.toggleOn": "Caméras en direct activées",
    "camera.toggleOff": "Caméras en direct désactivées",
    "camera.none": "Aucune caméra publique gratuite pour cette ville",
    "camera.live": "En direct",
    "camera.still": "Image en direct",
    "camera.next": "Caméra suivante ({index}/{total})",
    "camera.pause": "Pause",
    "camera.play": "Lecture",
    "camera.off": "Les caméras en direct sont désactivées",
    "camera.throttled": "Recherche de caméra indisponible pour le moment",
    "camera.alt": "Image de caméra en direct : {place}",
    "camera.altGeneric": "Image de caméra en direct",
    "camera.distanceOne": "À {distance} km",
    "camera.distanceMany": "À {distance} km",
    "camera.attribution": "Caméra : {source}",
    "camera.offline": "Caméra indisponible",
    "camera.compareAria": "Caméras en direct pour les emplacements comparés",
    "cameraHub.heading": "Villes avec webcams en direct",
    "cameraHub.subtitle": "Parcourez les caméras publiques gratuites par ville et consultez le climat du jour à côté des images.",
    "cameraHub.total": "{count} villes · {sources} sources",
    "cameraHub.filterLabel": "Filtrer les villes avec caméras",
    "cameraHub.filterPlaceholder": "Londres, Seattle, Toronto...",
    "cameraHub.loading": "Recherche des villes avec caméras publiques gratuites...",
    "cameraHub.loadingCity": "Ouverture des caméras...",
    "cameraHub.catalogueAria": "Villes avec caméras en direct",
    "cameraHub.wallAria": "Caméras en direct dans la ville sélectionnée",
    "cameraHub.backAll": "Toutes les villes avec caméras",
    "cameraHub.openForecast": "Ouvrir les prévisions complètes",
    "cameraHub.climateHeading": "Météo du jour",
    "cameraHub.cityCountOne": "{count} ville",
    "cameraHub.cityCountMany": "{count} villes",
    "cameraHub.cameraCountOne": "{count} caméra",
    "cameraHub.cameraCountMany": "{count} caméras",
    "cameraHub.hasCameras": "Caméras en direct disponibles",
    "cameraHub.empty": "Aucune ville avec caméra ne correspond à « {query} ».",
    "cameraHub.unavailable": "Impossible d'accéder au répertoire des caméras pour le moment.",
    "cameraHub.throttled": "Le répertoire limite les requêtes. Veuillez réessayer dans un instant.",
    "cameraHub.noFrames": "Aucune image de caméra n'est disponible pour {city} pour le moment.",
    "cameraHub.noForecast": "Impossible de trouver les prévisions pour {city}.",
    "cameraHub.snapshotNote": "Ces sources fournissent des images fixes, pas une vidéo. Les images sont actualisées environ toutes les {seconds} secondes.",
    "cameraHub.wallCount": "Affichage de {shown} caméras sur {total}",
    "cameraHub.pageCount": "Groupe de caméras {page} sur {pages}",
    "cameraHub.previousCameras": "Caméras précédentes",
    "cameraHub.nextCameras": "Autres caméras",
    "cameraHub.externalVideoNote": "Les vidéos en direct sont hébergées par SkylineWebcams. Leurs conditions autorisent le partage de liens ; le lecteur officiel s'ouvre dans un nouvel onglet.",
    "cameraHub.externalVideoCount": "{count} liens vidéo en direct",
    "cameraHub.continuousVideo": "Vidéo en direct continue",
    "cameraHub.watchExternal": "Regarder sur SkylineWebcams ↗",
    "climate.emptyHint": "Essayez une condition plus large comme « Ensoleillé », « Chaud » ou « Nuageux ».",
    "climate.viewDetails": "Afficher les détails de la météo",
    "climate.cardHumidityTitle": "Humidité relative",
    "climate.cardWindTitle": "Vitesse du vent",
    "climate.backToMatching": "Retour aux villes correspondantes ({count} trouvé)",
    "climate.searchWorldwide": "Rechercher les villes du monde correspondant à \"{query}\" →",
    "climate.discovery": "Découverte du climat",
    "climate.searching": "Recherche de villes dans le monde correspondant au climat préféré...",
    "climate.errorTitle": "Erreur de recherche climatique",
    "climate.errorBody": "Échec de la récupération des données météorologiques mondiales. Veuillez réessayer.",
    "state.fetching": "Récupération de données météorologiques en direct...",
    "state.fetchingCity": "Récupération de la météo en direct pour {city}...",
    "state.errorTitle": "Aucun résultat correspondant",
    "state.errorBody": "Nous n'avons pas pu récupérer les résultats de votre requête. Veuillez ajuster vos critères et réessayer.",
    "state.retry": "Essayez une autre recherche",
    "state.backToResults": "Retour aux résultats climatiques",
    "state.weatherUnavailableTitle": "Données météorologiques indisponibles",
    "state.weatherUnavailableBody": "Impossible de récupérer la météo pour \"{city}\". La demande a peut-être expiré. Veuillez vérifier votre connexion Internet et réessayer.",
    "state.cityNotFoundTitle": "Ville introuvable",
    "state.cityNotFoundBody": "Aucun résultat trouvé pour \"{city}\". Essayez de rechercher avec une orthographe différente ou d'ajouter un pays.",
    "state.searchFailedTitle": "Échec de la recherche",
    "state.searchTimedOut": "La demande de recherche a expiré. Veuillez vérifier votre connexion Internet et réessayer.",
    "state.searchFailed": "Une erreur s'est produite lors de la recherche de la ville. Veuillez réessayer.",
    "geo.button": "Utiliser l'emplacement actuel",
    "geo.detecting": "Détection de votre situation géographique...",
    "geo.unsupportedTitle": "Géolocalisation non prise en charge",
    "geo.unsupported": "Votre navigateur ne prend pas en charge la détection automatique de localisation.",
    "geo.deniedTitle": "Accès à la localisation refusé",
    "geo.denied": "Impossible de récupérer votre position. Veuillez vérifier les autorisations du navigateur ou rechercher directement votre ville.",
    "geo.myLocation": "Ma position",
    "compare.heading": "Comparer les emplacements",
    "compare.count": "{selected} sur {max} sélectionnés",
    "compare.subtitle": "Recherchez ci-dessus ou appuyez sur une ville populaire pour créer une liste, puis comparez 2 à 4 lieux.",
    "compare.addLocation": "Ajouter un emplacement",
    "compare.run": "Comparer",
    "compare.clearAll": "Tout effacer",
    "compare.loading": "Comparaison de la météo...",
    "compare.glanceHeading": "La météo en un coup d'œil",
    "compare.legendHigh": "Le plus haut de la rangée",
    "compare.legendLow": "Le plus bas de la rangée",
    "compare.currentHeading": "Conditions actuelles",
    "compare.forecastHeading": "Comparaison des prévisions du jour",
    "compare.forecastSubtitle": "Valeurs maximales, minimales, probabilité de pluie et valeurs maximales",
    "compare.metricHead": "Métrique",
    "compare.locationSlot": "Localisation {slot}",
    "compare.locationSlotEmpty": "Emplacement {slot} — utilisez la recherche ci-dessus ou une ville populaire",
    "compare.add": "Ajouter",
    "compare.moveEarlier": "Déplacer plus tôt",
    "compare.moveLater": "Déplacer plus tard",
    "compare.removeCity": "Supprimer {city} de la comparaison",
    "compare.clearSlot": "Effacer cet emplacement",
    "compare.unknownLocation": "Lieu inconnu",
    "compare.selectedLocation": "Emplacement sélectionné",
    "compare.changeLocation": "{city}, {meta}. Changez cet emplacement.",
    "compare.locationFallback": "Emplacement",
    "compare.weatherUnavailable": "Météo indisponible",
    "compare.tryAgain": "Essayer à nouveau",
    "compare.retryAria": "Réessayez de charger la météo pour {city}",
    "compare.thisLocation": "cet endroit",
    "compare.highest": "le plus élevé",
    "compare.lowest": "le plus bas",
    "compare.ariaExtreme": "{value}, {word} des emplacements comparés",
    "compare.ariaExtremeTitle": "{word} pour {row}",
    "compare.freshness": "Dernière lecture : {label}",
    "compare.needTwoLocations": "Au moins deux emplacements avec des données en direct sont nécessaires pour une comparaison.",
    "compare.verySimilar": "Ces emplacements sont actuellement très similaires – aucune différence ne ressort.",
    "compare.duplicate": "{city} est déjà dans votre comparaison.",
    "compare.listFull": "Vous pouvez comparer jusqu’à des emplacements {max}. Supprimez-en un pour en ajouter un autre.",
    "compare.couldNotAdd": "Cet emplacement n'a pas pu être ajouté à la comparaison.",
    "compare.replacing": "Choix d'un nouvel emplacement pour l'emplacement {slot} (actuellement {city}). Appuyez sur Échap pour annuler.",
    "compare.noResults": "Aucun résultat trouvé pour \"{query}\". Essayez une orthographe différente ou ajoutez un pays.",
    "compare.searchTimedOut": "La recherche de localisation a expiré. Vérifiez votre connexion et réessayez.",
    "compare.searchFailed": "La recherche de localisation a échoué. Veuillez réessayer.",
    "compare.locationZone": "Fuseau horaire local {zone}, {diff}",
    "glance.heading": "Aujourd'hui en un coup d'oeil",
    "glance.feelsLike": "On a l'impression",
    "glance.verdictLabel": "Le verdict du jour :",
    "glance.whatToWear": "Que porter :",
    "hero.feelsLike": "On a l'impression",
    "hero.shareAria": "Partager la météo",
    "hero.refreshAria": "Actualiser les données météo",
    "metrics.aria": "Indicateurs météorologiques clés",
    "metrics.heading": "Conditions actuelles",
    "metrics.humidity": "Humidité",
    "metrics.wind": "Vent",
    "metrics.uvIndex": "Indice UV",
    "metrics.pressure": "Pression",
    "metrics.precipitation": "Précipitation",
    "metrics.localTime": "Heure locale",
    "metrics.sunriseSunset": "Lever et coucher du soleil",
    "metrics.sunrise": "Lever du soleil",
    "metrics.sunset": "Coucher de soleil",
    "metrics.cloudCover": "Couverture nuageuse : {value}%",
    "metrics.humidityDry": "Environnement sec",
    "metrics.humidityComfortable": "Humidité confortable",
    "metrics.humidityHigh": "Humidité élevée",
    "metrics.pressureNormal": "Pression normale",
    "metrics.pressureHigh": "Système haute pression",
    "metrics.pressureLow": "Système basse pression",
    "metrics.uvLow": "Faible",
    "metrics.uvModerate": "Modéré",
    "metrics.uvHigh": "Haut",
    "metrics.uvVeryHigh": "Très élevé",
    "metrics.uvExtreme": "Extrême",
    "metrics.uvAdviceLow": "Faible risque de dommages causés par le soleil",
    "metrics.uvAdviceModerate": "Protection solaire conseillée",
    "metrics.uvAdviceHigh": "Portez un chapeau et de la crème solaire",
    "metrics.uvAdviceVeryHigh": "Évitez le soleil à midi",
    "metrics.uvAdviceExtreme": "Prenez des précautions en plein soleil",
    "forecast.hourlyHeading": "Prévisions sur 24 heures",
    "forecast.hourlySubtitle": "Projection horaire locale ·",
    "forecast.dailyHeading": "Prévisions sur 7 jours",
    "forecast.dailySubtitle": "Perspectives à venir ·",
    "forecast.cityTime": "heure locale de la ville",
    "forecast.hourlyAria": "Prévisions météo horaires",
    "forecast.now": "Maintenant",
    "forecast.today": "Aujourd'hui",
    "forecast.maxUvTitle": "Indice UV maximum",
    "forecast.precipChanceTitle": "Risque de précipitations",
    "popular.label": "Populaire:",
    "footer.providedBy": "Données fournies par {link}",
    "footer.tagline": "Intelligence météorologique mondiale en temps réel",
    "footer.timezoneNote": "Les heures locales utilisent le fuseau horaire IANA de chaque ville et cochent en temps réel · Votre heure de référence est détectée à partir du fuseau horaire de votre appareil ({zone})",
    "time.sameAsYou": "Même heure que vous",
    "time.sameAsYouShort": "Même heure",
    "time.aheadOf": "{value} d’avance sur vous",
    "time.behind": "{value} de retard sur vous",
    "time.detectedZone": "Fuseau horaire détecté : {zone}",
    "time.localTimeAria": "Votre heure locale, détectée à partir de votre fuseau horaire {zone}",
    "time.youClock": "Chez vous : {time}",
    "time.yourZoneTitle": "Votre fuseau horaire : {zone}",
    "time.allTimesIn": "Toutes les heures dans {zone}",
    "nav.detectedLocation": "Emplacement détecté",
    "nav.yourIP": "Votre IP",
    "nav.countryCity": "{country}, {city}",
    "time.offsetVsYou": "Décalage par rapport à vous ({zone}) : {value}",
    "time.freshnessNow": "Mis à jour tout à l'heure",
    "time.freshnessMinutes": "Mis à jour il y a {count} min",
    "time.freshnessHours": "Mis à jour il y a {count} heure",
    "time.freshnessHoursPlural": "Mis à jour il y a {count} heures",
    "time.freshnessDays": "Mis à jour il y a {count} jour",
    "time.freshnessDaysPlural": "Mis à jour il y a {count} jours",
    "share.forecast": "Prévisions partagées",
    "share.showAllCards": "Afficher toutes les cartes",
    "share.button": "Partager la météo",
    "share.weatherIn": "Météo à {place}",
    "share.rain": "{value}% de risque de pluie",
    "share.high": "Maximum : {value}",
    "share.low": "Minimum : {value}",
    "share.copied": "Lien copié. Son ouverture affiche {place} avec les cartes partagées.",
    "share.copyFailedInBar": "Impossible de copier automatiquement. Le lien pour {place} se trouve désormais dans la barre d'adresse.",
    "share.copyFailed": "Impossible de copier automatiquement. Copiez le lien de la barre d'adresse pour partager cette prévision.",
    "wmo.0": "Ciel clair",
    "wmo.1": "Principalement clair",
    "wmo.2": "Partiellement nuageux",
    "wmo.3": "Couvert",
    "wmo.45": "Brumeux",
    "wmo.48": "Brouillard de givre",
    "wmo.51": "Légère bruine",
    "wmo.53": "Bruine modérée",
    "wmo.55": "Bruine dense",
    "wmo.56": "Bruine verglaçante",
    "wmo.57": "Bruine verglaçante dense",
    "wmo.61": "Légère pluie",
    "wmo.63": "Pluie modérée",
    "wmo.65": "Forte pluie",
    "wmo.66": "Pluie verglaçante",
    "wmo.67": "Fortes pluies verglaçantes",
    "wmo.71": "Légère neige",
    "wmo.73": "Neige modérée",
    "wmo.75": "Fortes chutes de neige",
    "wmo.77": "Grains de neige",
    "wmo.80": "Légères averses de pluie",
    "wmo.81": "Averses de pluie modérées",
    "wmo.82": "Violentes averses de pluie",
    "wmo.85": "Averses de neige",
    "wmo.86": "Fortes averses de neige",
    "wmo.95": "Orage",
    "wmo.96": "Orage avec grêle",
    "wmo.99": "Fort orage avec grêle",
    "wmo.unknown": "Clair",
    "glanceEngine.storm": "Des orages attendus",
    "glanceEngine.snow": "Il neige aujourd'hui",
    "glanceEngine.freezing": "Un froid glacial",
    "glanceEngine.hot": "Très chaud",
    "glanceEngine.umbrella": "Parapluie recommandé",
    "glanceEngine.gale": "Très venteux",
    "glanceEngine.good": "Beau temps",
    "glanceEngine.around": "autour de {time}",
    "glanceEngine.at": "à {time}",
    "glanceEngine.detailStorm": "Des orages sont prévus{when} – les projets extérieurs pourraient être interrompus.",
    "glanceEngine.detailSnow": "De la neige est prévue{when} — prévoyez un temps de trajet supplémentaire.",
    "glanceEngine.detailFreezing": "On dirait {temp}{when} – des couches lourdes sont nécessaires.",
    "glanceEngine.detailHot": "On dirait {temp}{when} – cherchez de l’ombre et hydratez-vous.",
    "glanceEngine.detailRainNow": "La pluie tombe en ce moment ({amount} dans la dernière heure).",
    "glanceEngine.detailRainNowShort": "La pluie tombe en ce moment.",
    "glanceEngine.detailRainPeak": "La pluie culmine à {value}{when}.",
    "glanceEngine.detailLightPrecip": "De légères précipitations sont attendues aujourd'hui.",
    "glanceEngine.detailWinds": "Les vents atteignent {value} aujourd’hui – une journée venteuse.",
    "glanceEngine.detailVeryWindy": "Beaucoup de vent aujourd'hui.",
    "glanceEngine.detailMostlyDry": "Plutôt sec",
    "glanceEngine.detailDry": "Sec",
    "glanceEngine.detailComfortable": "et confortable autour de {value}",
    "glanceEngine.detailWithWind": "avec {value}",
    "glanceEngine.windLight": "vent léger",
    "glanceEngine.windBreeze": "une brise légère",
    "glanceEngine.windStrong": "vent fort",
    "glanceEngine.windVeryStrong": "vent très fort",
    "glanceEngine.metricRain": "Pluie",
    "glanceEngine.metricWind": "Vent",
    "glanceEngine.metricHumidity": "Humidité",
    "glanceEngine.hintPeakToday": "chance maximale aujourd'hui",
    "glanceEngine.hintNotReported": "non signalé",
    "glanceEngine.hintRelativeHumidity": "humidité relative",
    "compareEngine.metricCondition": "Météo",
    "compareEngine.metricTemperature": "Température",
    "compareEngine.metricApparent": "Température ressentie",
    "compareEngine.metricRainChance": "Risque de pluie",
    "compareEngine.metricWind": "Vent",
    "compareEngine.metricPressure": "Pression",
    "compareEngine.metricCloudCover": "Couverture nuageuse",
    "compareEngine.metricSun": "Lever/coucher du soleil",
    "compareEngine.metricPrecipitation": "Précipitation",
    "compareEngine.metricUv": "Indice UV",
    "compareEngine.metricMaxUv": "UV maximum",
    "compareEngine.metricMaxWind": "Vent maximum",
    "compareEngine.warmer": "plus chaud",
    "compareEngine.cooler": "plus frais",
    "compareEngine.insightTemperature": "{city} est {gap} {word} plutôt que {other}.",
    "compareEngine.insightApparent": "On ressent {gap} {word} dans {city} plutôt que dans {other}.",
    "compareEngine.insightRain": "{city} a le plus faible risque de pluie ({low} vs {high}).",
    "compareEngine.insightWind": "Le vent est {gap} plus fort à {city} qu'à {other}.",
    "compareEngine.insightPressure": "La pression atmosphérique est {gap} plus élevée dans {city} que dans {other}.",
    "compareEngine.insightCloud": "{city} est {gap} plus nuageux que {other}.",
    "compareEngine.insightSun": "Le soleil se lève à {gap} plus tôt à {city} qu'à {other}.",
    "compareEngine.insightPrecip": "{city} a {gap} plus de précipitations que {other}.",
    "compareEngine.insightUv": "L'indice UV est {gap} plus élevé dans {city} que dans {other}.",
    "compareEngine.insightMaxUv": "L'indice UV maximal d'aujourd'hui est {gap} plus élevé dans {city} que dans {other}.",
    "compareEngine.insightMaxWind": "Le vent le plus fort d'aujourd'hui est {gap} plus rapide à {city} qu'à {other}.",
    "compareEngine.gapWarmer": "plus chaud",
    "compareEngine.gapCooler": " plus frais",
    "compareEngine.gapStronger": "plus fort",
    "compareEngine.gapHigher": "plus haut",
    "compareEngine.gapCloudier": "plus nuageux",
    "compareEngine.gapEarlier": "plus tôt",
    "compareEngine.gapMore": "plus",
    "compareEngine.gapFaster": "plus rapide",
    "adviceEngine.windowMorning": "Matin",
    "adviceEngine.windowMidday": "Midi",
    "adviceEngine.windowAfternoon": "Après-midi",
    "adviceEngine.windowEvening": "Soirée",
    "adviceEngine.phraseMorning": "votre matinée",
    "adviceEngine.phraseMidday": "les heures de midi",
    "adviceEngine.phraseAfternoon": "votre après-midi",
    "adviceEngine.phraseEvening": "le soir",
    "adviceEngine.tileUmbrella": "Parapluie",
    "adviceEngine.tileWalk": "Marcher",
    "adviceEngine.tileCarWash": "Laver la voiture",
    "adviceEngine.tileCycling": "Vélo",
    "adviceEngine.tileSwimming": "Natation",
    "adviceEngine.tileClothing": "Que porter",
    "adviceEngine.summaryLabel": "Le conseil du jour",
    "adviceEngine.scopeToday": "le reste de la journée",
    "adviceEngine.scopeNext24": "les prochaines 24 heures",
    "adviceEngine.notEnoughTitle": "Pas assez de données prévisionnelles",
    "adviceEngine.notEnoughDetail": "Cette recommandation nécessite des données de prévision horaires qui ne sont pas disponibles actuellement.",
    "adviceEngine.noHourly": "Aucune prévision horaire utilisable n’est disponible.",
    "adviceEngine.noPrecip": "Cette ville n'a aucune probabilité ni quantité de précipitations dans les prévisions.",
    "adviceEngine.noTemperatures": "Aucune température horaire utilisable n’est disponible.",
    "adviceEngine.noStretch": "Pas assez de températures horaires pour comparer une partie de la journée.",
    "adviceEngine.noDaylight": "Aucune température horaire de l’air n’est disponible pour les heures de clarté.",
    "adviceEngine.noPeriodTemp": "Aucune température horaire n'est disponible pour cette période.",
    "adviceEngine.notCalculated": "Cette recommandation n'a pas pu être calculée à partir des prévisions actuelles.",
    "adviceEngine.summaryNotCalculated": "Ce résumé n'a pas pu être calculé à partir des prévisions actuelles.",
    "adviceEngine.umbrellaDefinitely": "Apportez certainement un parapluie",
    "adviceEngine.umbrellaLikely": "Apportez un parapluie",
    "adviceEngine.umbrellaUnlikely": "Probablement pas",
    "adviceEngine.walkNone": "Pas de période idéale aujourd'hui",
    "adviceEngine.walkLimited": "Détails limités pour cette période",
    "adviceEngine.walkReasonWind": "il y a du vent",
    "adviceEngine.walkBest": "La période la plus sèche est {window}. {reasons}",
    "adviceEngine.walkBestPlain": "La période la plus sèche est {window}.",
    "adviceEngine.walkBut": "{detail}, mais {reasons}.",
    "adviceEngine.carWashGood": "Bonne journée pour laver la voiture",
    "adviceEngine.carWashBad": "Pas idéal aujourd'hui",
    "adviceEngine.carWashRainLater": "De la pluie est attendue{when}{amount}.",
    "adviceEngine.carWashUnsettled": "Un temps humide ou instable est attendu toute la journée.",
    "adviceEngine.carWashDrySpells": "Les périodes de sécheresse sont trop courtes pour en valoir la peine.{hint}",
    "adviceEngine.cyclingBad": "Pas idéal pour faire du vélo",
    "adviceEngine.cyclingWind": "Des vents forts d’environ {wind}{when} sont attendus.",
    "adviceEngine.cyclingRain": "{amount}",
    "adviceEngine.cyclingCold": "Très froid pour rouler - autour de {temp}.",
    "adviceEngine.cyclingHot": "Très chaud pour rouler - jusqu'à {temp}.",
    "adviceEngine.cyclingGood": "Bon pour le vélo",
    "adviceEngine.cyclingGoodDetail": "{temps}temps sec et vents relativement faibles.",
    "adviceEngine.swimBad": "Pas idéal aujourd'hui",
    "adviceEngine.swimRain": "{amount} Il est préférable de rester hors de l'eau.",
    "adviceEngine.swimCold": "Frais pour la baignade en plein air - air autour de {temp} au mieux.",
    "adviceEngine.swimHot": "Air très chaud, jusqu'à {temp}. Restez à l'ombre entre les séances.",
    "adviceEngine.swimGood": "Beau temps pour la baignade en plein air",
    "adviceEngine.swimOvercast": "généralement couvert",
    "adviceEngine.clothingLight": "Vêtements légers",
    "adviceEngine.clothingWarm": "Chaud - autour de {temp} dans la partie la plus chaude de la journée.",
    "adviceEngine.clothingJacketUmbrella": "Veste chaude + parapluie",
    "adviceEngine.clothingJacketUmbrellaDetail": "Froid et humide - autour de {temp} avec de la pluie attendue.",
    "adviceEngine.clothingTShirtUmbrella": "T-shirt météo + parapluie",
    "adviceEngine.clothingTShirt": "Temps doux, tenue légère",
    "adviceEngine.clothingTShirtDetail": "Chaud et sec{wind}.",
    "adviceEngine.clothingTShirtWind": "avec des vents légers",
    "adviceEngine.clothingLightJacket": "Veste légère recommandée",
    "adviceEngine.clothingLightJacketDetail": "Temps doux : autour de {temp}.",
    "adviceEngine.clothingWarmJacket": "Veste chaude recommandée",
    "adviceEngine.clothingWarmJacketDetail": "Frais : autour de {temp}.",
    "adviceEngine.clothingCoat": "Manteau d'hiver recommandé",
    "adviceEngine.clothingCoatDetail": "Froid, autour de {temp}.",
    "adviceEngine.clothingLayers": "Couches très chaudes nécessaires",
    "adviceEngine.clothingLayersDetail": "Sous zéro, autour de {temp}.",
    "adviceEngine.uvNote": "Une protection solaire est conseillée.",
    "adviceEngine.swingNote": "Attendez-vous à une oscillation de {swing}°C aujourd'hui.",
    "adviceEngine.windNote": "Il y a du vent.",
    "adviceEngine.darkNote": "La majeure partie de la fenêtre de prévision restante se situe après la tombée de la nuit.",
    "adviceEngine.breezeNote": "Une légère brise est attendue.",
    "adviceEngine.tempsNote": "Températures autour de {temp}.",
    "adviceEngine.rainWindowPeriod": "De la pluie est prévue durant cette période.",
    "adviceEngine.rainWindowLight": "De légères précipitations sont possibles pendant cette période.",
    "adviceEngine.summarySnow": "Il neige aujourd'hui",
    "adviceEngine.summarySnowDetail": "De la neige est prévue aujourd'hui. Prévoyez un temps de trajet supplémentaire.",
    "adviceEngine.summaryStorm": "Des orages attendus",
    "adviceEngine.summaryStormDetail": "Des orages sont prévus aujourd'hui - les projets extérieurs pourraient être interrompus.",
    "adviceEngine.summaryUmbrella": "Prenez un parapluie aujourd'hui",
    "adviceEngine.summaryCold": "Il fait froid aujourd'hui",
    "adviceEngine.summaryHot": "Chaud aujourd'hui",
    "adviceEngine.summaryGreat": "Belle journée pour être dehors",
    "adviceEngine.summaryMixed": "Des conditions mitigées aujourd'hui",
    "adviceEngine.summaryMixedDetail": "Des passages instables sont probables{when} pendant {scope}.",
    "adviceEngine.summaryCloudyDry": "Nuageux mais sec aujourd'hui",
    "adviceEngine.summaryCloudyDryDetail": "Aucune pluie n'est prévue ; autour de {temp} avec {wind}.",
    "adviceEngine.summaryVariableWinds": "vents variables",
    "assistant.scopeNext24": "Basé sur les prochaines 24 heures",
    "assistant.scopeToday": "Basé sur le reste d'aujourd'hui",
    "assistant.heading": "Le conseil du jour",
    "assistant.preparing": "Préparation de vos prévisions…",
    "assistant.windowTitle": "Il pleut pendant votre… ?",
    "assistant.windowTitlePlain": "Pluie pendant votre...",
  };
  if (typeof module === 'object' && module.exports) module.exports = fr;
  if (root && root.I18n) root.I18n.translations.fr = fr;
})(typeof globalThis !== 'undefined' ? globalThis : this);
